use_frameworks!

platform :ios, '10.0'

target 'PDCollectionInfiteView_Example' do
  pod 'PDCollectionInfiteView', :path => '../'

  target 'PDCollectionInfiteView_Tests' do
    inherit! :search_paths

    
  end
end
